### ISSUE TITLE
How to reproduce the best result of imagenet top1 acc 76.4% 

### ISSUE THREAD

**Issue by ChienYiChi** [VITA-Group/GraNet#1]
I am trying to reproduce the best result in your paper with 250 epoch on ImageNet.
Below is the experiment that I had trained on ImageNet:
-  --sparse-init ERK --method GraNet --init-prune-epoch 0 \
    --final-prune-epoch 75 --init-density 0.5 \
    --final-density 0.1 --multiplier 1 \
    --growth gradient --seed 17 --master_port 5555 \
    -j5 -p 500 --arch resnet50 -c fanin \
    --update-frequency 4000 \
    --label-smoothing 0.1 -b 64 \
    --lr 0.5 --warmup 5 --density 0.1 $2 /ssd1/dataset/imagenet/ --epochs 250 
I set the final prune epoch to 75 which achieve 75.03% on Imagenet

It will be great if you could share the best configuration of the best result. 

Thank you !

**Comment by Shiweiliuiiiiiii** [comment]
Hi,

We have an argument "--multiplier" to control the training time easily. You can just set it to 2.5 to reproduce the results. In that case, the command should be
```
python $1multiproc.py --nproc_per_node 2 $1main.py --sparse --sparse-init ERK --method GraNet --init-prune-epoch 0 --final-prune-epoch 30 --init-density 0.5 --final-density 0.2 --multiplier 2.5 --growth gradient --seed 17 --master_port 5555 -j5 -p 500 --arch resnet50 -c fanin --update-frequency 4000 --label-smoothing 0.1 -b 64 --lr 0.1 --warmup 5 --density 0.2 $2 ../../imagenet2012/ --epochs 100 
```
Note that I ran the experiments with 2 GPUs, so that the actual batch size is 64*2=128. You might also need to make sure the batch size is 128.

**Comment by Shiweiliuiiiiiii** [comment]
Hi, Just for curiosity. Did you successfully reproduce our results?
